### ISSUE TITLE
Run time error 10: "Native function failed"

### ISSUE THREAD

**Issue by minhthien2563** [IllidanS4/PawnPlus#41]
Hi!

I have a bit of a problem with the PawnPlus library, the error described in the console is "Run time error 10:" Native function failed "", looking forward to your help.

![Capture](https://user-images.githubusercontent.com/51225849/97946240-64f88d80-1dbc-11eb-9af4-a5dee62d6bae.PNG)

```
InsertPhoneMessage(phoneid, targetid, targetphoneid, const content[])
{
    new
        str[600],
        hour, minute, second,
        year, month, day;
    
    new message[E_MESSAGE_PHONE];
    message[messagePhoneOwner] = targetphoneid;
    gettime(hour, minute, second);
    format(str, sizeof(str), "%02d:%02d:%02d", hour, minute, second);
    format(message[messageTime], sizeof message[messageTime], str);
    getdate(year, month, day);
    message[messageDay] = day;
    message[messageMonth] = month;
    message[messageYear] = year;
    message[messageNumberSender] = InfoPhone[phoneid][phoneNumber];
    format(message[messageContent], sizeof message[messageContent], content);

    return list_add_arr(messages, message);
}

```

**Comment by IllidanS4** [comment]
Hello, you haven't shown how you create `messages`. That code is probably at fault.

**Comment by minhthien2563** [comment]
Oh sorry.

```
new List:messages;

```

**Comment by IllidanS4** [comment]
You have to create an instance of the list in order to add elements to it, for example via `list_new`. Otherwise the variable will have the initial value of `INVALID_LIST` (`List:0`).

You can use the usual script initialization callback to create the list there, use an [initializer](https://github.com/IllidanS4/PawnPlus/wiki/Initializers-and-finalizers) or perform some sort of lazy loading (check if the list is `INVALID_LIST` and then create it).
