### ISSUE TITLE
Some underflow things

### ISSUE THREAD

**Issue by Banditul** [IllidanS4/PawnPlus#6]
Alright, i have the following plugins in my server.cfg `PawnPlus mysql sscanf streamer` but if i add PawnPlus to plugins list my login dialog dont work(wont apear at all) if i delete the PawnPlus from plugins the gamemode works perfect

If i add crashdetect too, after i connect to server this things pop out https://pastebin.com/bahkug22
If you need additional info just let me know

Note: I dont have PawnPlus included in my gamemode also i use the last version of your plugin

Edit: If i include PawnPlus in gamemode same thing occur

**Comment by IllidanS4** [comment]
Thanks for reporting; does this occur on both 0.8 and 0.7.2, or only on 0.8?

**Comment by Banditul** [comment]
Seems to occur only in 0.8, in 0.7.2 its work fine, even with crashdetect

**Comment by IllidanS4** [comment]
Both PawnPlus and SAMPGDK use negative function index in calls to `amx_Exec`. d73bf51 slightly changed how PawnPlus deals with unregistered events, which broke the previous (unintentialy) compatibility with SAMPGDK.

SAMPGDK uses indices less than -10000, so PawnPlus will only proceed with calling the event if it is larger. This is a temporary solution, since SAMPGDK may change the mechanism or other plugins could start using the range.
